// flow-typed signature: cdd611dba36f750c18e38e2ee95385d2
// flow-typed version: <<STUB>>/@testing-library/user-event_v^4.1.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/user-event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/user-event' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/user-event/__tests__/click' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/__tests__/dblclick' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/__tests__/selectoptions' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/__tests__/type' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/index' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/user-event/__tests__/click.js' {
  declare module.exports: $Exports<'@testing-library/user-event/__tests__/click'>;
}
declare module '@testing-library/user-event/__tests__/dblclick.js' {
  declare module.exports: $Exports<'@testing-library/user-event/__tests__/dblclick'>;
}
declare module '@testing-library/user-event/__tests__/selectoptions.js' {
  declare module.exports: $Exports<'@testing-library/user-event/__tests__/selectoptions'>;
}
declare module '@testing-library/user-event/__tests__/type.js' {
  declare module.exports: $Exports<'@testing-library/user-event/__tests__/type'>;
}
declare module '@testing-library/user-event/dist/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/index'>;
}
declare module '@testing-library/user-event/src/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/src/index'>;
}
