// flow-typed signature: 2e163310fa09a27720de7520671632ce
// flow-typed version: <<STUB>>/@testing-library/user-event_v^10.4.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/user-event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/user-event' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/user-event/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/user-event/dist/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist'>;
}
declare module '@testing-library/user-event/dist/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist'>;
}
