// flow-typed signature: 3bb6626ee1e002115a680d2f6b258535
// flow-typed version: <<STUB>>/@storybook/addon-a11y_v^6.3.7/flow_v0.157.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-a11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-a11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-a11y/dist/cjs/a11yHighlight' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/a11yRunner' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/A11yContext' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/A11YPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/ColorFilters' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/Report/Elements' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/Report/HighlightToggle' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/Report' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/Report/Info' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/Report/Item' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/Report/Rules' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/Report/Tags' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/Tabs' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/components/VisionSimulator' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/highlight' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/params' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/cjs/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/a11yHighlight' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/a11yRunner' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/A11yContext' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/A11YPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/ColorFilters' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/Report/Elements' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/Report/HighlightToggle' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/Report' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/Report/Info' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/Report/Item' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/Report/Rules' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/Report/Tags' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/Tabs' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/components/VisionSimulator' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/highlight' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/params' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/esm/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/a11yHighlight' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/a11yRunner' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/A11yContext' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/A11YPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/ColorFilters' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/Report/Elements' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/Report/HighlightToggle' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/Report' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/Report/Info' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/Report/Item' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/Report/Rules' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/Report/Tags' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/Tabs' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/components/VisionSimulator' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/highlight' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/params' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/modern/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-a11y/dist/cjs/a11yHighlight.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/a11yHighlight'>;
}
declare module '@storybook/addon-a11y/dist/cjs/a11yRunner.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/a11yRunner'>;
}
declare module '@storybook/addon-a11y/dist/cjs/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/addDecorator'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/A11yContext.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/A11yContext'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/A11YPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/A11YPanel'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/ColorFilters.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/ColorFilters'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/Report/Elements.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/Report/Elements'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/Report/HighlightToggle.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/Report/HighlightToggle'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/Report/index' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/Report'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/Report/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/Report'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/Report/Info.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/Report/Info'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/Report/Item.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/Report/Item'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/Report/Rules.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/Report/Rules'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/Report/Tags.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/Report/Tags'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/Tabs.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/Tabs'>;
}
declare module '@storybook/addon-a11y/dist/cjs/components/VisionSimulator.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/components/VisionSimulator'>;
}
declare module '@storybook/addon-a11y/dist/cjs/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/constants'>;
}
declare module '@storybook/addon-a11y/dist/cjs/highlight.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/highlight'>;
}
declare module '@storybook/addon-a11y/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs'>;
}
declare module '@storybook/addon-a11y/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs'>;
}
declare module '@storybook/addon-a11y/dist/cjs/params.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/params'>;
}
declare module '@storybook/addon-a11y/dist/cjs/register.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/register'>;
}
declare module '@storybook/addon-a11y/dist/cjs/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/cjs/typings.d'>;
}
declare module '@storybook/addon-a11y/dist/esm/a11yHighlight.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/a11yHighlight'>;
}
declare module '@storybook/addon-a11y/dist/esm/a11yRunner.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/a11yRunner'>;
}
declare module '@storybook/addon-a11y/dist/esm/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/addDecorator'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/A11yContext.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/A11yContext'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/A11YPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/A11YPanel'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/ColorFilters.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/ColorFilters'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/Report/Elements.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/Report/Elements'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/Report/HighlightToggle.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/Report/HighlightToggle'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/Report/index' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/Report'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/Report/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/Report'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/Report/Info.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/Report/Info'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/Report/Item.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/Report/Item'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/Report/Rules.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/Report/Rules'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/Report/Tags.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/Report/Tags'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/Tabs.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/Tabs'>;
}
declare module '@storybook/addon-a11y/dist/esm/components/VisionSimulator.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/components/VisionSimulator'>;
}
declare module '@storybook/addon-a11y/dist/esm/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/constants'>;
}
declare module '@storybook/addon-a11y/dist/esm/highlight.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/highlight'>;
}
declare module '@storybook/addon-a11y/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm'>;
}
declare module '@storybook/addon-a11y/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm'>;
}
declare module '@storybook/addon-a11y/dist/esm/params.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/params'>;
}
declare module '@storybook/addon-a11y/dist/esm/register.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/register'>;
}
declare module '@storybook/addon-a11y/dist/esm/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/esm/typings.d'>;
}
declare module '@storybook/addon-a11y/dist/modern/a11yHighlight.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/a11yHighlight'>;
}
declare module '@storybook/addon-a11y/dist/modern/a11yRunner.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/a11yRunner'>;
}
declare module '@storybook/addon-a11y/dist/modern/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/addDecorator'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/A11yContext.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/A11yContext'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/A11YPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/A11YPanel'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/ColorFilters.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/ColorFilters'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/Report/Elements.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/Report/Elements'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/Report/HighlightToggle.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/Report/HighlightToggle'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/Report/index' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/Report'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/Report/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/Report'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/Report/Info.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/Report/Info'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/Report/Item.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/Report/Item'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/Report/Rules.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/Report/Rules'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/Report/Tags.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/Report/Tags'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/Tabs.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/Tabs'>;
}
declare module '@storybook/addon-a11y/dist/modern/components/VisionSimulator.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/components/VisionSimulator'>;
}
declare module '@storybook/addon-a11y/dist/modern/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/constants'>;
}
declare module '@storybook/addon-a11y/dist/modern/highlight.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/highlight'>;
}
declare module '@storybook/addon-a11y/dist/modern/index' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern'>;
}
declare module '@storybook/addon-a11y/dist/modern/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern'>;
}
declare module '@storybook/addon-a11y/dist/modern/params.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/params'>;
}
declare module '@storybook/addon-a11y/dist/modern/register.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/register'>;
}
declare module '@storybook/addon-a11y/dist/modern/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/modern/typings.d'>;
}
declare module '@storybook/addon-a11y/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/preset'>;
}
declare module '@storybook/addon-a11y/register.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/register'>;
}
