// flow-typed signature: aadeb38812fe110adcad1e3fb2586fe1
// flow-typed version: <<STUB>>/@storybook/addons_v^6.3.7/flow_v0.157.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addons/dist/cjs/hooks' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/cjs/make-decorator' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/cjs/public_api' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/cjs/storybook-channel-mock' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/cjs/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/esm/hooks' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/esm/make-decorator' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/esm/public_api' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/esm/storybook-channel-mock' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/esm/types' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/esm/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/modern/hooks' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/modern' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/modern/make-decorator' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/modern/public_api' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/modern/storybook-channel-mock' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/modern/types' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/modern/typings.d' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addons/dist/cjs/hooks.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/cjs/hooks'>;
}
declare module '@storybook/addons/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/addons/dist/cjs'>;
}
declare module '@storybook/addons/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/cjs'>;
}
declare module '@storybook/addons/dist/cjs/make-decorator.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/cjs/make-decorator'>;
}
declare module '@storybook/addons/dist/cjs/public_api.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/cjs/public_api'>;
}
declare module '@storybook/addons/dist/cjs/storybook-channel-mock.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/cjs/storybook-channel-mock'>;
}
declare module '@storybook/addons/dist/cjs/types.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/cjs/types'>;
}
declare module '@storybook/addons/dist/cjs/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/cjs/typings.d'>;
}
declare module '@storybook/addons/dist/esm/hooks.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/esm/hooks'>;
}
declare module '@storybook/addons/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/addons/dist/esm'>;
}
declare module '@storybook/addons/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/esm'>;
}
declare module '@storybook/addons/dist/esm/make-decorator.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/esm/make-decorator'>;
}
declare module '@storybook/addons/dist/esm/public_api.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/esm/public_api'>;
}
declare module '@storybook/addons/dist/esm/storybook-channel-mock.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/esm/storybook-channel-mock'>;
}
declare module '@storybook/addons/dist/esm/types.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/esm/types'>;
}
declare module '@storybook/addons/dist/esm/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/esm/typings.d'>;
}
declare module '@storybook/addons/dist/modern/hooks.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/modern/hooks'>;
}
declare module '@storybook/addons/dist/modern/index' {
  declare module.exports: $Exports<'@storybook/addons/dist/modern'>;
}
declare module '@storybook/addons/dist/modern/index.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/modern'>;
}
declare module '@storybook/addons/dist/modern/make-decorator.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/modern/make-decorator'>;
}
declare module '@storybook/addons/dist/modern/public_api.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/modern/public_api'>;
}
declare module '@storybook/addons/dist/modern/storybook-channel-mock.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/modern/storybook-channel-mock'>;
}
declare module '@storybook/addons/dist/modern/types.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/modern/types'>;
}
declare module '@storybook/addons/dist/modern/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/modern/typings.d'>;
}
