// flow-typed signature: 692286bda96b0ab6dd590db8cc9c6cd6
// flow-typed version: <<STUB>>/@storybook/addon-knobs_v^6.2.9/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-knobs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-knobs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-knobs/dist/cjs/__types__/knob-test-cases' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/PropForm' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Boolean' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Button' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Checkboxes' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Color' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Date' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Files' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Number' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Object' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Options' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Radio' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Select' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/Text' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/components/types/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/converters' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/KnobManager' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/KnobStore' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/preset/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/registerKnobs' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/shared' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/title' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/type-defs' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/cjs/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/__types__/knob-test-cases' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/PropForm' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Boolean' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Button' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Checkboxes' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Color' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Date' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Files' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Number' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Object' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Options' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Radio' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Select' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/Text' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/components/types/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/converters' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/KnobManager' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/KnobStore' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/preset/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/registerKnobs' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/shared' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/title' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/type-defs' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/esm/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-knobs/dist/cjs/__types__/knob-test-cases.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/__types__/knob-test-cases'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/Panel'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/PropForm.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/PropForm'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Array'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Boolean.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Boolean'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Button.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Button'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Checkboxes.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Checkboxes'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Color.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Color'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Date.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Date'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Files.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Files'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/index' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Number.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Number'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Object.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Object'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Options.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Options'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Radio.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Radio'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Select.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Select'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/Text.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/Text'>;
}
declare module '@storybook/addon-knobs/dist/cjs/components/types/types.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/components/types/types'>;
}
declare module '@storybook/addon-knobs/dist/cjs/converters.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/converters'>;
}
declare module '@storybook/addon-knobs/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs'>;
}
declare module '@storybook/addon-knobs/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs'>;
}
declare module '@storybook/addon-knobs/dist/cjs/KnobManager.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/KnobManager'>;
}
declare module '@storybook/addon-knobs/dist/cjs/KnobStore.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/KnobStore'>;
}
declare module '@storybook/addon-knobs/dist/cjs/preset/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/preset/addDecorator'>;
}
declare module '@storybook/addon-knobs/dist/cjs/register.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/register'>;
}
declare module '@storybook/addon-knobs/dist/cjs/registerKnobs.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/registerKnobs'>;
}
declare module '@storybook/addon-knobs/dist/cjs/shared.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/shared'>;
}
declare module '@storybook/addon-knobs/dist/cjs/title.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/title'>;
}
declare module '@storybook/addon-knobs/dist/cjs/type-defs.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/type-defs'>;
}
declare module '@storybook/addon-knobs/dist/cjs/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/cjs/typings.d'>;
}
declare module '@storybook/addon-knobs/dist/esm/__types__/knob-test-cases.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/__types__/knob-test-cases'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/Panel'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/PropForm.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/PropForm'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Array'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Boolean.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Boolean'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Button.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Button'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Checkboxes.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Checkboxes'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Color.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Color'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Date.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Date'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Files.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Files'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/index' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Number.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Number'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Object.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Object'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Options.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Options'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Radio.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Radio'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Select.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Select'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/Text.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/Text'>;
}
declare module '@storybook/addon-knobs/dist/esm/components/types/types.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/components/types/types'>;
}
declare module '@storybook/addon-knobs/dist/esm/converters.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/converters'>;
}
declare module '@storybook/addon-knobs/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm'>;
}
declare module '@storybook/addon-knobs/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm'>;
}
declare module '@storybook/addon-knobs/dist/esm/KnobManager.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/KnobManager'>;
}
declare module '@storybook/addon-knobs/dist/esm/KnobStore.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/KnobStore'>;
}
declare module '@storybook/addon-knobs/dist/esm/preset/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/preset/addDecorator'>;
}
declare module '@storybook/addon-knobs/dist/esm/register.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/register'>;
}
declare module '@storybook/addon-knobs/dist/esm/registerKnobs.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/registerKnobs'>;
}
declare module '@storybook/addon-knobs/dist/esm/shared.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/shared'>;
}
declare module '@storybook/addon-knobs/dist/esm/title.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/title'>;
}
declare module '@storybook/addon-knobs/dist/esm/type-defs.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/type-defs'>;
}
declare module '@storybook/addon-knobs/dist/esm/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/esm/typings.d'>;
}
declare module '@storybook/addon-knobs/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/preset'>;
}
declare module '@storybook/addon-knobs/register.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/register'>;
}
